task_name: cot_compositional_transform
task_files:
  - data/generation/code/apis/glaive/detection/single_api/qna.yaml
  - data/generation/code/apis/glaive/detection/yes_no/qna.yaml
  - data/generation/code/apis/glaive/sequencing/parallel_multiple/qna.yaml
  - data/generation/code/sql/nl2sql/orders/qna.yaml
  - data/transformation/cot/qna.yaml
tasks:
  api_single_detection:
    instruction_format:
      input: "<|function_call_library|>\n{{api_specifications}}\n\nUSER: {{input}}\nASSISTANT: "
      output: "{{output}}"
  api_yes_no:
    instruction_format:
      input: "<|function_call_library|>\n{{api_specifications}}\n\nUSER: {{input}}\nASSISTANT: "
      output: "{{output}}"
  api_parallel_multiple:
    instruction_format:
      input: "<|function_call_library|>\n{{api_specifications}}\n\nUSER: {{input}}\nASSISTANT: "
      output: "{{output}}"
  nl2sql_orders:
    instruction_format:
      input: "{{instruction}}"
      output: "{{output}}"
  cot_transform:
    instruction_format:
      input: "INPUT: {{input}}\nTHOUGHT: {{thought}}\nOUTPUT: "
      output: "{{output}}"
dependencies:
  cot_transform:
    - api_single_detection
    - api_yes_no
    - api_parallel_multiple
    - nl2sql_orders
